version: '3'

services:

  opentsdb:
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30
    ports:
      - "4242:4242"
      - "60030:60030"
    volumes:
      - "/Users/darraghconnaughton/Github/thirdParty/opentsdb-docker/data:/data/hbase"
    networks:
      - internal-network


  monitor:
    image: docker-monitor:latest
    ports:
      - "1234:1234"
    networks:
      - internal-network
    depends_on:
      - opentsdb

  dashserver:
    image: docker-dashserver:latest
    ports:
      - "8080:8080"
    networks:
      - internal-network
    depends_on:
      - opentsdb


  controlproxy:
    image: docker-controlproxy:latest
    ports:
      - "8886:8886"
    networks:
      - internal-network
    depends_on:
      - opentsdb

  forwardproxy:
    image: docker-forwardproxy:latest
    ports:
      - "8888:8888"
      - "8889:8889"
    networks:
      - internal-network
    depends_on:
      - opentsdb


networks:
  internal-network:
